version: '3'

services:
  node-app:
    image: node:18.17.0
    hostname: nextplay
    container_name: nextplay
    environment:
    - VIRTUAL_HOST=nextplay.syntapse.co.uk
    - LETSENCRYPT_HOST=nextplay.syntapse.co.uk
    - LETSENCRYPT_EMAIL=laurencefass@syntapse.co.uk
    expose:
      - "3000"
    volumes:
      - .:/app
    working_dir: /app
    # command: tail -f /dev/null
    command: "npm run dev"
    networks:
      main-net: 

networks:
  main-net:
    external:
      name: proxy_main-net