version: '3'

services:
  node-app:
    image: node:18.17.0
    hostname: nextplay
    container_name: nextplay
    environment:
    # ${VAR_XXX} are required system env vars - add them to ~./bashrc
    - VIRTUAL_HOST=nextplay.${LETSENCRYPT_HOST}
    - LETSENCRYPT_HOST=nextplay.${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    volumes:
      - .:/app
    working_dir: /app
    # command: tail -f /dev/null
    command: "npm run dev"
    networks:
      main-net: 

networks:
  main-net:
    external:
      name: proxy_main-net